### Numpy 基础运算

#### 数组下标操作

使用$Numpy$初始化数组

In [1]:
import numpy as np

arr = np.arange(16)

arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

- 获取单个元素

In [2]:
arr[0]

0

- 区间取数

In [3]:
arr[2:4]

array([2, 3])

- 区间跳跃取数

In [4]:
arr[2:10:2]

array([2, 4, 6, 8])

- 利用数组作为下表访问元素

In [5]:
idx = [1,4,6]
arr[idx]

array([1, 4, 6])

- 数组下标操作后可以变成二维数据

In [6]:
new_idx = np.array(
    [[0,2],
    [1,3]]
)

arr[new_idx]

array([[0, 2],
       [1, 3]])

- 转化为二维矩阵

In [7]:
new_arr = arr.reshape(4,-1)

new_arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

- 二维矩阵取数

In [8]:
row = np.array([0,1,2])

col = np.array([0,0,0])

new_arr[row,col]

array([0, 4, 8])

-  $bool$数组取数

In [9]:
bool_col = [True,False,True,False]

new_arr[1:3,bool_col]

array([[ 4,  6],
       [ 8, 10]])

#### 数组比较操作

In [10]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

- 直接使用运算符,或者稍微复杂点的运算

In [11]:
arr < 3

array([ True,  True,  True, False, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [12]:
2 * arr == 24 - 4 * arr

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False])

- 直接进行统计运算

In [13]:
np.sum(arr <= 3)

4

- 统计非零元素

In [14]:
np.count_nonzero(arr)

15

- 有一个满足则返回True

In [15]:
np.any(arr == 114)

np.any(arr < 0)

False

- 必须全部满足,才能返回True

In [16]:
np.any(arr >= 0)

True

In [17]:
new_arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

- 行处理 axis = 1

In [18]:
np.sum(new_arr%2==0,axis = 1)

array([2, 2, 2, 2])

- 列处理 axis = 0

In [19]:
np.sum(new_arr % 2 == 0,axis = 0)

array([4, 0, 4, 0])

- 多条件链接

In [20]:
np.sum((arr > 3) & (arr < 6))

2

- 非运算

In [21]:
np.sum(~(arr ==1))

15